/**
 * Topic cluster data for Quadratics and related mathematical concepts
 * Defines the galaxy map structure with interconnected topics
 */

import { Topic, QuizQuestion } from './types';

/**
 * Complete topic cluster for Quadratics
 * Each topic has a position in the galaxy map and connections to related topics
 * The center topic (Quadratic Equations) is unlocked by default
 */
export const QUADRATICS_CLUSTER: Topic[] = [
  {
    id: 'quadratic-equations',
    name: 'Quadratic Equations',
    description: 'Understanding equations of the form ax² + bx + c = 0',
    difficulty: 'beginner',
    position: { x: 0, y: 0 }, // Center of the galaxy
    connectedTopics: ['quadratic-formula', 'parabola-graphs', 'factorization'],
    captured: false,
    unlocked: true, // Starting point
    color: '#3b82f6', // Blue
  },
  {
    id: 'quadratic-formula',
    name: 'Quadratic Formula',
    description: 'Solving quadratics using x = (-b ± √(b²-4ac)) / 2a',
    difficulty: 'beginner',
    position: { x: 150, y: -100 },
    connectedTopics: ['quadratic-equations', 'discriminant', 'complex-roots'],
    captured: false,
    unlocked: false,
    color: '#8b5cf6', // Purple
  },
  {
    id: 'parabola-graphs',
    name: 'Parabola Graphs',
    description: 'Visual representation of quadratic functions',
    difficulty: 'beginner',
    position: { x: -150, y: -100 },
    connectedTopics: ['quadratic-equations', 'vertex-form', 'real-world-applications'],
    captured: false,
    unlocked: false,
    color: '#ec4899', // Pink
  },
  {
    id: 'vertex-form',
    name: 'Vertex Form',
    description: 'Expressing quadratics as a(x-h)² + k',
    difficulty: 'intermediate',
    position: { x: -200, y: 50 },
    connectedTopics: ['parabola-graphs', 'completing-square'],
    captured: false,
    unlocked: false,
    color: '#f59e0b', // Amber
  },
  {
    id: 'completing-square',
    name: 'Completing the Square',
    description: 'Algebraic technique to convert to vertex form',
    difficulty: 'intermediate',
    position: { x: -100, y: 150 },
    connectedTopics: ['vertex-form', 'quadratic-formula', 'quadratic-equations'],
    captured: false,
    unlocked: false,
    color: '#10b981', // Emerald
  },
  {
    id: 'discriminant',
    name: 'Discriminant',
    description: 'Understanding b² - 4ac and nature of roots',
    difficulty: 'intermediate',
    position: { x: 200, y: 50 },
    connectedTopics: ['quadratic-formula', 'complex-roots'],
    captured: false,
    unlocked: false,
    color: '#06b6d4', // Cyan
  },
  {
    id: 'factorization',
    name: 'Factorization',
    description: 'Breaking down quadratics into (x-p)(x-q) form',
    difficulty: 'beginner',
    position: { x: 100, y: 150 },
    connectedTopics: ['quadratic-equations', 'quadratic-formula'],
    captured: false,
    unlocked: false,
    color: '#14b8a6', // Teal
  },
  {
    id: 'real-world-applications',
    name: 'Real-World Applications',
    description: 'Using quadratics in physics, engineering, and economics',
    difficulty: 'advanced',
    position: { x: -250, y: -200 },
    connectedTopics: ['parabola-graphs', 'vertex-form'],
    captured: false,
    unlocked: false,
    color: '#f97316', // Orange
  },
  {
    id: 'complex-roots',
    name: 'Complex Roots',
    description: 'Understanding solutions when discriminant is negative',
    difficulty: 'advanced',
    position: { x: 250, y: -200 },
    connectedTopics: ['discriminant', 'quadratic-formula'],
    captured: false,
    unlocked: false,
    color: '#a855f7', // Purple
  },
];

/**
 * Get a topic by its ID
 */
export const getTopicById = (id: string): Topic | undefined => {
  return QUADRATICS_CLUSTER.find((topic) => topic.id === id);
};

/**
 * Get all topics connected to a given topic
 */
export const getConnectedTopics = (topicId: string): Topic[] => {
  const topic = getTopicById(topicId);
  if (!topic) return [];
  
  return topic.connectedTopics
    .map((id) => getTopicById(id))
    .filter((t): t is Topic => t !== undefined);
};

/**
 * Check if a topic should be unlocked based on captured topics
 * A topic is unlocked if at least one of its connected topics is captured
 */
export const shouldUnlockTopic = (topicId: string, capturedTopics: string[]): boolean => {
  const topic = getTopicById(topicId);
  if (!topic) return false;
  
  // Already unlocked topics stay unlocked
  if (topic.unlocked) return true;
  
  // Check if any connected topic is captured
  return topic.connectedTopics.some((connectedId) => capturedTopics.includes(connectedId));
};

/**
 * Get quiz questions for a specific topic
 * In production, these would be generated by AI or fetched from a database
 */
export const getQuizQuestions = (topicId: string): QuizQuestion[] => {
  const quizBank: Record<string, QuizQuestion[]> = {
    'quadratic-equations': [
      {
        id: 'qe-1',
        question: 'What is the standard form of a quadratic equation?',
        options: ['ax + b = 0', 'ax² + bx + c = 0', 'ax³ + bx² + c = 0', 'ax² = 0'],
        correctAnswer: 1,
        explanation: 'The standard form is ax² + bx + c = 0, where a ≠ 0.',
      },
      {
        id: 'qe-2',
        question: 'In the equation 3x² - 5x + 2 = 0, what is the value of coefficient "a"?',
        options: ['2', '-5', '3', '0'],
        correctAnswer: 2,
        explanation: 'The coefficient "a" is the number multiplying x², which is 3.',
      },
      {
        id: 'qe-3',
        question: 'Which of these is NOT a quadratic equation?',
        options: ['x² + 5x = 0', '2x² - 3 = 0', 'x + 7 = 0', 'x² = 16'],
        correctAnswer: 2,
        explanation: 'x + 7 = 0 is a linear equation because it has no x² term.',
      },
    ],
    'quadratic-formula': [
      {
        id: 'qf-1',
        question: 'What is the quadratic formula?',
        options: [
          'x = -b / 2a',
          'x = (-b ± √(b²-4ac)) / 2a',
          'x = (b ± √(b²+4ac)) / 2a',
          'x = -b ± √(b²-4ac)',
        ],
        correctAnswer: 1,
        explanation: 'The quadratic formula is x = (-b ± √(b²-4ac)) / 2a.',
      },
      {
        id: 'qf-2',
        question: 'The quadratic formula can be used to solve which type of equations?',
        options: ['Only factorable quadratics', 'Any quadratic equation', 'Only linear equations', 'Only perfect squares'],
        correctAnswer: 1,
        explanation: 'The quadratic formula works for ANY quadratic equation, even when factoring is difficult.',
      },
    ],
    'parabola-graphs': [
      {
        id: 'pg-1',
        question: 'What shape does a quadratic function create when graphed?',
        options: ['A straight line', 'A parabola', 'A circle', 'A hyperbola'],
        correctAnswer: 1,
        explanation: 'Quadratic functions always create a U-shaped curve called a parabola.',
      },
      {
        id: 'pg-2',
        question: 'If a > 0 in y = ax² + bx + c, the parabola opens:',
        options: ['Downward', 'Upward', 'To the left', 'To the right'],
        correctAnswer: 1,
        explanation: 'When a > 0, the parabola opens upward (smiling face).',
      },
    ],
  };

  return quizBank[topicId] || [];
};